name: link-check

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check links
        id: lc
        uses: peter-evans/link-checker@v1.2.2
        with:
          args: -v -r *

      - name: Fail on invalid links
        run: exit ${{ steps.lc.outputs.exit_code }}
